### ISSUE TITLE
Cannot add a datasource

### ISSUE THREAD

**Issue by ktalebian** [JamesOsgood/mongodb-grafana#138]
I'm running Grafana OSS locally via Docker. I cloned this project in this location `/opt/homebrew/Cellar/grafana/9.3.6/share/grafana/public/app/plugins/datasource/mongodb-grafana` and restarted the app.

When I visit localhost:3000 to access Grafana and add a datasource, MongoDB shows up but it is not clickable - I cannot configure it.

What seems to be he issue?

**Comment by josephjacobmorris** [comment]
I am also facing the same issue, It is showing up in the grafana/grafana-oss:9.2.7 UI  but on clicking nothing happens
![image](https://user-images.githubusercontent.com/48655639/221759487-8c605114-5a26-4bd8-ba7d-791508931ffc.png)


My docker-compose.yml is like this :
```yml
  datastore:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    restart: always


  grafana:
    image:
      joseph/grafana-mongodb:v1
    container_name: monitoring_grafana
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - config.grafana
```

and the docker is built using this Dockerfile
```Dockerfile
FROM  grafana/grafana-oss:9.2.7

COPY ./grafana.ini /etc/grafana/grafana.ini

COPY ./mongodb-grafana /var/lib/grafana/plugins/
```
and in ```grafana.ini``` I have updated ```allow_loading_unsigned_plugins =grafana-mongodb-datasource``` to allow the unsigned plugin.

But Why I am not able to use this as datasource?
